#To create an EC2 Instance
#ARNAmeTP-YAML
#resources demo

AWSTemplateFormatVersion: 2010-09-09
Resources: 
  MyEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-0cd3dfa4e37921605
    InstanceType: t2.micro
    KeyName: linux-key
    SecurityGroups: 
      -default
      - !Ref SSHSecurityGroup

  

  SSHSecurityGroup:
    Properties:
    GroupDescription: my new sg
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp 
        FromPort: '8080'
        ToPort: '8080'
        CidrIp: 0.0.0.0/0

  MyElasticIp:
    Type: AWS::EC2::EIP
    Properites: 
      InstanceId: !Ref MyEC2Instance    

